version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Config dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "./build.gradle" }}
#      - run:
#          name: Build and run tests
#          command: ./gradlew build jacocoTestReport
#      - run:
#          name: Analyze on Sonarqube
#          command: ./gradlew sonarqube
workflows:
  main:
    jobs:
      - build:
          context:
            - SonarCloud